# Generated by Django 3.2.4 on 2021-06-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210616_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
